sudo: required

addons:
    chrome: stable

language: node_js

services:
    - docker

node_js:
    - "10"

env:
    global:
        - NODE_ENV=test
        - EZMASTER_PUBLIC_URL=http://localhost:3000

dist: trusty

cache:
    directories:
        - node_modules
        - ~/.cache/Cypress
        - ~/node_modules/.cache/
        - ~/node_modules/.cache/@babel/register/


install:
    - "make install"

script:
    - make test
