language: node_js

node_js:
    - "7.8.0"

env:
    global:
        - NODE_ENV=test

dist: trusty

cache:
    directories:
        - node_modules

before_script:
    - cp ./config/test-dist.js ./config/test.js
    - docker-compose -f docker-compose.unit.yml up -d mongo api
    - sleep 10

install:
    - "make --silent install"
