language: node_js

services:
    - docker

node_js:
    - "8.9.1"

env:
    global:
        - NODE_ENV=test
        - EZMASTER_PUBLIC_URL=http://localhost:3000

dist: trusty

cache:
    directories:
        - node_modules

install:
    - "make install"

script:
    - make test
