sudo: required

addons:
    chrome: stable

language: node_js

services:
    - docker

node_js:
    - '10'

env:
    global:
        - NODE_ENV=test
        - EZMASTER_PUBLIC_URL=http://localhost:3000

dist: trusty

cache:
    directories:
        - node_modules
        - ~/.cache/Cypress
        - ~/node_modules/.cache/
        - ~/node_modules/.cache/@babel/register/

install:
    - make install

stages:
    - name: test

jobs:
    include:
        - stage: test
          name: 'Unit Tests'
          env: NODE_ENV=test
          script:
              - make test-unit

        - stage: test
          name: 'API E2E Tests'
          env: NODE_ENV=test
          script:
              - make test-api-e2e

        - stage: test
          name: 'E2E Tests'
          env: NODE_ENV=test
          script:
              - make test-e2e
