npm:
    image: node:7.4.0
    volumes:
        - .:/app
    working_dir: /app
    environment:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: "localhost,127.0.0.1,"
    entrypoint: ['npm']
