version: "2"
services:
    node:
        image: node:8.9.1
        volumes:
            - .:/app
        working_dir: /app
        environment:
            http_proxy: ${http_proxy}
            https_proxy: ${https_proxy}
            no_proxy: "localhost,127.0.0.1,"
            NODE_ENV: ${NODE_ENV}
            EZMASTER_PUBLIC_URL: ${EZMASTER_PUBLIC_URL}
        links:
            - mongo

    api:
        image: node:8.9.1
        volumes:
            - .:/app
        working_dir: /app
        environment:
            NODE_ENV: ${NODE_ENV}
            http_proxy: ${http_proxy}
            https_proxy: ${https_proxy}
            no_proxy: "localhost,127.0.0.1,"
            EZMASTER_PUBLIC_URL: ${EZMASTER_PUBLIC_URL}
        links:
            - mongo
        ports:
            - 3000:3000
        command: npm run development:api

    mongo:
        image: mongo:3.0.14
        command: "--smallfiles"
        ports:
            - 27017:27017
