version: "2"

services:
    api:
        image: node:7.8.0
        volumes:
            - .:/app
        working_dir: /app
        environment:
            NODE_APP_INSTANCE: test
            NODE_ENV: test
            http_proxy:  ${http_proxy}
            https_proxy: ${https_proxy}
            no_proxy: "localhost,127.0.0.1,api,hub,chrome,mongo"
        links:
            - mongo
        command: node --harmony-async-await --require babel-register ./src/api

    mongo:
        image: mongo:3.0.14
        command: "--smallfiles"
