version: "3"
services:
    api:
        build: .
        environment:
            EZMASTER_PUBLIC_URL: ${EZMASTER_PUBLIC_URL}
            EZMASTER_MONGODB_HOST_PORT: mongo:27017
        links:
            - mongo
        depends_on:
            - mongo
        ports:
            - 3000:3000

    mongo:
        image: mongo:3.0.14
        command: "--smallfiles"
