name: Test unit
on:
  push:
    branches:
    - *
  pull_request:
    - master

jobs:
  test-unit:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Intell lodex
      run: make install

    - name: Start containers
      run: NODE_ENV=test docker-compose -f docker-compose.dev.yml run --no-deps -d

    - name: Start test unit
      run: npm run test:unit

    - name: Stop containers
      if: always()
      run: docker-compose -f docker-compose.dev.yml down

